### ISSUE TITLE
Fix `NullPointerException` when using known entities inside projections.

### ISSUE THREAD

**Issue by pelletier197** [spring-projects/spring-data-neo4j#2349]
I'm experiencing some issues with the latest version `6.1.3` with the mapping that has changed. The following does not work anymore: 

```kotlin
@Node("Person")
data class PersonEntity(
    @Id
    val id: String,
    val email: String,
)

@Node("Department")
data class DepartmentEntity(
    @Id
    val id: String,
    val name: String
)


data class PersonDepartmentQueryResult(
    val person: PersonEntity,
    val department: DepartmentEntity,
)

interface PersonRepository : Neo4jRepository<PersonEntity, String> {
    @Query(
        """
        MATCH (person:Person)-[:MEMBER_OF]->(department:Department)
        RETURN person, department
    """
    )
    fun findPersonWithDepartment(): List<PersonQueryResult>
}

@Service
class TestService(
    personRepo: PersonRepository,
) {
    init {
            println(personRepo.findPersonWithDepartment())
    }
}
```

which produces the following stacktrace : 
```
Caused by: java.lang.NullPointerException: null
	at org.springframework.data.neo4j.core.PropertyFilterSupport.processEntity(PropertyFilterSupport.java:125)
	at org.springframework.data.neo4j.core.PropertyFilterSupport.addPropertiesFrom(PropertyFilterSupport.java:100)
	at org.springframework.data.neo4j.core.PropertyFilterSupport.getInputProperties(PropertyFilterSupport.java:54)
	at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:90)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
```
It tries to fetch the `department` field in the `person` entity, and `PropertyFilterSupport` doesn't handle the null `persistentProperty`. 

I'm pretty sure this bug was introduced with the `multi-level` projection support: https://github.com/spring-projects/spring-data-neo4j/pull/2314 

This exact query works in 6.1.2, so my expectations for the behaviour would be that this keeps working with 6.1.3.

Thank you!

**Comment by michael-simons** [comment]
> It tries to fetch the department field in the person entity, and PropertyFilterSupport doesn't handle the null persistentProperty.

I see no such field in the class you shared. 

Can you please share a small reproducer? Thanks.

**Comment by pelletier197** [comment]
There is no field in the person entity. This is wished for us for performance purpose. I showed something really simplified compared to our use case, but we can't put the field in the entity. The code I shared will produce the NPE.

**Comment by michael-simons** [comment]
The code you shared is incomplete, however I try to investigate nevertheless.

**Comment by michael-simons** [comment]
Reproduced and fixed. Will be available in the next 6.1 patch release. Thank you very much for your report.
